const fs = require("node:fs");
const path = require("node:path");
const { spawn } = require("node:child_process");
const dotenv = require("dotenv");

const generatedLocalEnvMarker = "# generated by npm run start:tunnel";

// Start with shell environment (excluding npm_ vars)
const env = Object.fromEntries(
  Object.entries(process.env).filter(([key]) => !key.startsWith("npm_"))
);

delete env.NODE;
delete env.INIT_CWD;

// Layer 1: Load .env file (base configuration)
const envPath = path.join(process.cwd(), ".env");
if (fs.existsSync(envPath)) {
  const dotenvConfig = dotenv.parse(fs.readFileSync(envPath));
  Object.assign(env, dotenvConfig);
  console.log("[Expo] Loaded .env");
}

const hostMode = process.env.EXPO_HOST_MODE;
const localEnvPath = path.join(process.cwd(), ".env.local");

function removeGeneratedLocalEnv() {
  if (!fs.existsSync(localEnvPath)) return;

  const existingContent = fs.readFileSync(localEnvPath, "utf8");
  if (existingContent.startsWith(generatedLocalEnvMarker)) {
    fs.unlinkSync(localEnvPath);
    console.log("[Expo] Removed generated .env.local");
  }
}

// Layer 2: Load .env.api-tunnel only when the tunnel command is used.
const apiTunnelEnvPath = path.join(process.cwd(), ".env.api-tunnel");
if (hostMode === "tunnel" && fs.existsSync(apiTunnelEnvPath)) {
  const tunnelConfig = dotenv.parse(fs.readFileSync(apiTunnelEnvPath));
  Object.assign(env, tunnelConfig);
  console.log(`[Expo] Loaded .env.api-tunnel: ${tunnelConfig.EXPO_PUBLIC_API_URL}`);

  const localEnvContent = `${generatedLocalEnvMarker}\nEXPO_PUBLIC_API_URL=${tunnelConfig.EXPO_PUBLIC_API_URL}\n`;
  fs.writeFileSync(localEnvPath, localEnvContent);
  console.log(`[Expo] Wrote .env.local for Expo with ${tunnelConfig.EXPO_PUBLIC_API_URL}`);
} else {
  removeGeneratedLocalEnv();
}

const hostArgs = hostMode === "tunnel"
  ? ["--tunnel"]
  : hostMode === "lan"
    ? ["--lan"]
    : [];

if (hostMode === "tunnel") {
  const expoNgrokPreloadPath = path.join(process.cwd(), "scripts/expo-ngrok-system-bin.js");
  const existingNodeOptions = env.NODE_OPTIONS ? `${env.NODE_OPTIONS} ` : "";
  env.NODE_OPTIONS = `${existingNodeOptions}--require=${JSON.stringify(expoNgrokPreloadPath)}`;
  console.log("[Expo] Using system ngrok for Expo tunnel");
}

const args = ["expo", "start", "--clear", "--port", "8081", ...hostArgs, ...process.argv.slice(2)];
const command = process.platform === "win32" ? "npx.cmd" : "npx";

const child = spawn(command, args, {
  env,
  stdio: "inherit"
});

child.on("exit", (code, signal) => {
  if (signal) {
    process.kill(process.pid, signal);
    return;
  }
  process.exit(code ?? 0);
});
